name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "macOS 10.15 + Xcode 11.7"
            os: macos-10.15
            compiler: xcode
            version: "11.7"
          - name: "macOS 10.15 + Xcode 12.2"
            os: macos-10.15
            compiler: xcode
            version: "12.2"

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure Compiler
      run: |
        ls -ls /Applications/
        sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
    - name: Install Conan Package Manager
      shell: bash
      run: |
        brew install conan
    - name: Configure Build
      run: |
        mkdir build
        conan install . -if build --build missing -s build_type=Release
        cd build && cmake .. -DCUBBYFLOW_INSTALL_DIR=${{ github.workspace }}/Libraries/cubbyflow -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: /Users/runner/work/RenderFlow/RenderFlow/build/bin/UnitTests