name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "macOS 10.15 + Xcode 11.7"
            os: macos-10.15
            compiler: xcode
            version: "11.7"
          - name: "macOS 10.15 + Xcode 12.2"
            os: macos-10.15
            compiler: xcode
            version: "12.2"

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure Compiler
      run: |
        ls -ls /Applications/
        sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install cxxopts:x64-osx glad[gl-api-45]:x64-osx glfw3:x64-osx glm:x64-osx imgui:x64-osx tinyobjloader:x64-osx
        ./vcpkg/vcpkg integrate install
        mv vcpkg /Users/runner/work
        echo "vcpkg_path=/Users/runner/work/vcpkg" >> $GITHUB_ENV
    - name: Configure Build
      run: |
        mkdir build
        ${{ env.vcpkg_path }}/vcpkg list
        cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ env.vcpkg_path }}/scripts/buildsystems/vcpkg.cmake -DCUBBYFLOW_INSTALL_DIR=${{ github.workspace }}/Libraries/cubbyflow -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: /Users/runner/work/RenderFlow/RenderFlow/build/bin/UnitTests