name: macOS

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "macOS 10.15 + Xcode 11.7"
            os: macos-10.15
            compiler: xcode
            version: "11.7"
          - name: "macOS 10.15 + Xcode 12.2"
            os: macos-10.15
            compiler: xcode
            version: "12.2"
          - name: "macOS 10.15 + gcc-8"
            os: macos-10.15
            compiler: gcc
            version: "8"
          - name: "macOS 10.15 + gcc-9"
            os: macos-10.15
            compiler: gcc
            version: "9"

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure Compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
        else
          ls -ls /Applications/
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        fi
    - name: Install Dependencies
      if: startsWith(matrix.compiler, "gcc")
      run: |
        sudo xcode-select --install
        sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        sudo brew doctor
        export HOMEBREW_NO_ANALYTICS=1
        sudo brew update
        sudo brew upgrade
        sudo brew info gcc-${{ matrix.version }}
        sudo brew install gcc-${{ matrix.version }}
        sudo brew cleanup
    - name: Configure Build
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cd build && make