name: Ubuntu CodeCoverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "Ubuntu 20.04 + GCC-9"
            os: ubuntu-20.04
            compiler: gcc
            version: "9"

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Dependency
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install lcov xorg-dev freeglut3-dev
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo apt-get install cmake gcc-${{ matrix.version }} g++-${{ matrix.version }}
        else
          sudo apt-get install cmake clang-${{ matrix.version }} clang++-${{ matrix.version }}
        fi
    - name: Configure Compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
        else
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
        fi
    - name: Install Conan Package Manager
      shell: bash
      run: |
        pip3 install conan
    - name: Configure Build
      run: |
        mkdir build
        conan install . -if build --build missing -s build_type=Debug
        cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_COVERAGE=ON
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: /home/runner/work/RenderFlow/RenderFlow/build/bin/UnitTests
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)