name: Window

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "Windows Server 2019 + Visual Studio 2019"
            os: windows-2019

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Conan Package Manager
      run: |
        pip install conan
    - name: Configure Build
      run: |
        mkdir build
        conan install . -if build --build missing -s build_type=Release
        cd build && cmake .. -DCMAKE_GENERATOR_PLATFORM=x64 -DCUBBYFLOW_INSTALL_DIR=${GITHUB_WORKSPACE}/Libraries/cubbyflow -DCMAKE_BUILD_TYPE=Release
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: cd build && MSBuild.exe RenderFlow.sln /p:Configuration=Release
    - name: Run Unit Test
      run: /a/RenderFlow/RenderFlow/build/bin/Release/UnitTests.exe