name: Window

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "Windows Server 2019 + Visual Studio 2019"
            os: windows-2019

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        vcpkg install cxxopts:x64-windows glad[gl-api-45]:x64-windows glfw3:x64-windows glm:x64-windows imgui:x64-windows tinyobjloader:x64-windows
        vcpkg integrate install
    - name: Configure Build
      run: |
        mkdir build
        C:/vcpkg/vcpkg list
        cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCUBBYFLOW_INSTALL_DIR=${{ github.workspace }}/Libraries/cubbyflow -DCMAKE_BUILD_TYPE=Release
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: cd build && MSBuild.exe RenderFlow.sln /p:Configuration=Release
    - name: Run Unit Test
      run: /a/RenderFlow/RenderFlow/build/bin/Release/UnitTests.exe